version: '3.1'

services:
  mongo:
    image: mongo
    container_name: chatroom-mongodb
    restart: always
    ports:
      - "27020:27017"
    networks:
      - backend
    volumes:
      - "/tmp/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234567
    
  mongo-express:
    image: mongo-express
    container_name: chatroom-mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - backend
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: chatroom-mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234567
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234567

  backendserver:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: chatroom-backend-server
    restart: always
    depends_on:
      - mongo
    networks:
      - backend
    volumes:
      - /tmp/docker_backend

networks:
  backend: